apiVersion: v1
kind: Service
metadata:
  name: {{ include "semantic-router.fullname" . }}
  namespace: {{ include "semantic-router.namespace" . }}
  labels:
    {{- include "semantic-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.grpc.port }}
    targetPort: {{ .Values.service.grpc.name }}
    protocol: TCP
    name: {{ .Values.service.grpc.name }}
  - port: {{ .Values.service.api.port }}
    targetPort: {{ .Values.service.api.name }}
    protocol: TCP
    name: {{ .Values.service.api.name }}
  selector:
    {{- include "semantic-router.selectorLabels" . | nindent 4 }}
---
{{- if .Values.service.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "semantic-router.fullname" . }}-metrics
  namespace: {{ include "semantic-router.namespace" . }}
  labels:
    {{- include "semantic-router.labels" . | nindent 4 }}
    service: metrics
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.metrics.port }}
    targetPort: {{ .Values.service.metrics.name }}
    protocol: TCP
    name: {{ .Values.service.metrics.name }}
  selector:
    {{- include "semantic-router.selectorLabels" . | nindent 4 }}
{{- end }}
